// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtEVXA69i6JKtb3YgTgvJnAOo1AJWYBYc',
    appId: '1:558563212965:web:0b2b01b35ec33d4f45974c',
    messagingSenderId: '558563212965',
    projectId: 'navigatorapp-cfc3a',
    authDomain: 'navigatorapp-cfc3a.firebaseapp.com',
    storageBucket: 'navigatorapp-cfc3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwt9tNTBtWkCdfkPWi1WknlaJQ8zVhQIo',
    appId: '1:558563212965:android:456570da1049cf5045974c',
    messagingSenderId: '558563212965',
    projectId: 'navigatorapp-cfc3a',
    storageBucket: 'navigatorapp-cfc3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDk4aEGAPLWkrKVkBPOruFoYmZ7bGcGBg',
    appId: '1:558563212965:ios:962af0e9ae1b530045974c',
    messagingSenderId: '558563212965',
    projectId: 'navigatorapp-cfc3a',
    storageBucket: 'navigatorapp-cfc3a.appspot.com',
    iosBundleId: 'com.example.navigatorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDk4aEGAPLWkrKVkBPOruFoYmZ7bGcGBg',
    appId: '1:558563212965:ios:962af0e9ae1b530045974c',
    messagingSenderId: '558563212965',
    projectId: 'navigatorapp-cfc3a',
    storageBucket: 'navigatorapp-cfc3a.appspot.com',
    iosBundleId: 'com.example.navigatorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtEVXA69i6JKtb3YgTgvJnAOo1AJWYBYc',
    appId: '1:558563212965:web:98c349bc2ea0661045974c',
    messagingSenderId: '558563212965',
    projectId: 'navigatorapp-cfc3a',
    authDomain: 'navigatorapp-cfc3a.firebaseapp.com',
    storageBucket: 'navigatorapp-cfc3a.appspot.com',
  );
}
